spring:

  jpa:
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: superpassword
    driver-class-name: org.postgresql.Driver

server:
  port: 8085